import "dotenv/config";

export const config = {
  token: process.env.DISCORD_TOKEN ?? "",
  clientId: process.env.CLIENT_ID ?? "",
  guildId: process.env.GUILD_ID ?? "",
  staffRoleId: process.env.STAFF_ROLE_ID ?? "",
  verifyRoleId: process.env.VERIFY_ROLE_ID ?? process.env.VERIFIED_ROLE_ID ?? "",
  javaVerifiedRoleId: process.env.JAVA_VERIFIED_ROLE_ID ?? "",
  bedrockVerifiedRoleId: process.env.BEDROCK_VERIFIED_ROLE_ID ?? "",
  ticketCategoryId: process.env.TICKET_CATEGORY_ID ?? "",
  eventApplicationCategoryId: process.env.EVENT_APPLICATION_CATEGORY_ID ?? "",
  ticketLogsChannelId: process.env.TICKET_LOGS_CHANNEL_ID ?? "",
  diamondSupporterRoleId: process.env.DIAMOND_SUPPORTER_ROLE_ID ?? "",
  ironSupporterRoleId: process.env.IRON_SUPPORTER_ROLE_ID ?? "",
  dirtSupporterRoleId: process.env.DIRT_SUPPORTER_ROLE_ID ?? "",
  eventLogsChannelId: process.env.EVENT_LOGS_CHANNEL_ID ?? "",
  auditLogsChannelId: process.env.AUDIT_LOGS_CHANNEL_ID ?? process.env.LOG_CHANNEL_ID ?? "",
  verificationLogsChannelId: process.env.VERIFICATION_LOG_CHANNEL_ID ?? "",
  welcomeChannelId: process.env.WELCOME_CHANNEL_ID ?? "",
  welcomeBannerUrl: process.env.WELCOME_BANNER_URL ?? process.env.WELCOME_IMAGE_URL ?? "",
  welcomeRoleId: process.env.WELCOME_ROLE_ID ?? "",
  rulesChannelId: process.env.RULES_CHANNEL_ID ?? "",
  aboutChannelId: process.env.ABOUT_CHANNEL_ID ?? "",
  rolesChannelId: process.env.ROLES_CHANNEL_ID ?? "",
  bedrockChannelId: process.env.BEDROCK_CHANNEL_ID ?? "",
  announcementsChannelId: process.env.ANNOUNCEMENTS_CHANNEL_ID ?? "",
  ipChannelId: process.env.IP_CHANNEL_ID ?? "",
  mcHost: process.env.SERVER_IP ?? process.env.MC_HOST ?? "glurps.net",
  mcPort: Number(process.env.SERVER_PORT ?? process.env.MC_PORT ?? 50349),
  publicMinecraftAddress: process.env.NEXT_PUBLIC_MINECRAFT_ADDRESS ?? "glurps.net",
  discordInviteUrl: process.env.NEXT_PUBLIC_DISCORD_INVITE_URL ?? ""
};
