import {randomUUID} from 'node:crypto';
import {ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,type ButtonInteraction,type StringSelectMenuInteraction,type ModalSubmitInteraction,type ChatInputCommandInteraction,type Role,type TextChannel} from 'discord.js';
import {sqlite} from '../../database/database.js';
import {glurpsEmbed} from '../../utils/embeds.js';
sqlite.exec(`CREATE TABLE IF NOT EXISTS color_picker_panels(id TEXT PRIMARY KEY,guild_id TEXT NOT NULL,channel_id TEXT NOT NULL,message_id TEXT NOT NULL,role_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS color_picker_drafts(panel_id TEXT NOT NULL,user_id TEXT NOT NULL,hex TEXT NOT NULL,PRIMARY KEY(panel_id,user_id));
CREATE TABLE IF NOT EXISTS role_color_history(guild_id TEXT NOT NULL,role_id TEXT NOT NULL,user_id TEXT NOT NULL,old_color INTEGER NOT NULL,new_color INTEGER NOT NULL,created_at INTEGER NOT NULL);`);
type Panel={id:string;guild_id:string;channel_id:string;message_id:string;role_id:string};
export function hexColor(value:string){const hex=value.trim().replace(/^#/,'').replace(/^0x/i,'');if(!/^[a-f\d]{3}$|^[a-f\d]{6}$/i.test(hex))throw new Error('Enter a 3- or 6-digit hex code, like #A78BFA.');const full=hex.length===3?hex.split('').map(c=>c+c).join(''):hex;return Math.max(1,parseInt(full,16));}
export function colorHex(value:number){return '#'+value.toString(16).padStart(6,'0').toUpperCase();}
export function brightness(value:number,amount:number){const channels=[value>>16,(value>>8)&255,value&255].map(c=>Math.round(amount>0?c+(255-c)*amount:c*(1+amount)));return Math.max(1,(channels[0]<<16)+(channels[1]<<8)+channels[2]);}
const presets=[['Discord Blue','5865F2'],['Sky','38BDF8'],['Ocean','0284C7'],['Teal','14B8A6'],['Mint','6EE7B7'],['Emerald','10B981'],['Lime','A3E635'],['Gold','FACC15'],['Amber','F59E0B'],['Orange','F97316'],['Coral','FB7185'],['Red','EF4444'],['Rose','F43F5E'],['Pink','EC4899'],['Lavender','A78BFA'],['Purple','8B5CF6'],['Indigo','6366F1'],['Cream','FEF3C7'],['White','F8FAFC'],['Silver','94A3B8'],['Slate','475569'],['Near Black','010101']];
export class ColorPickerService {
 private locks=new Set<string>();
 private panel(id:string){return sqlite.prepare('SELECT * FROM color_picker_panels WHERE id=?').get(id) as Panel|undefined;}
 private async target(i:ButtonInteraction|StringSelectMenuInteraction|ModalSubmitInteraction,panelId:string,owner?:string){const p=this.panel(panelId);if(!p || p.guild_id!==i.guildId || p.channel_id!==i.channelId || (owner && owner!==i.user.id))throw new Error('This colour picker is unavailable. Open your own preview from the panel.');const role=await i.guild!.roles.fetch(p.role_id);if(!role || role.managed || !role.editable)throw new Error('I can no longer edit that role. Move it below my highest role.');return {p,role};}
 private getDraft(id:string,userId:string,role:Role){const row=sqlite.prepare('SELECT hex FROM color_picker_drafts WHERE panel_id=? AND user_id=?').get(id,userId) as {hex:string}|undefined;return row?hexColor(row.hex):role.color||0x5865f2;}
 private save(id:string,userId:string,value:number){sqlite.prepare('INSERT OR REPLACE INTO color_picker_drafts VALUES (?,?,?)').run(id,userId,colorHex(value));}
 publicPayload(id:string,role:Role){return {embeds:[glurpsEmbed().setColor(role.color||0x5865f2).setTitle('🎨 Role Colour Studio').setDescription(`Choose a colour for <@&${role.id}>.\n\n**Current colour:** \`${colorHex(role.color)}\`\nPreview presets, enter a hex code, or fine-tune the brightness. Your preview is private; **Apply Colour** changes the role for everyone who has it.`).setFooter({text:'Anyone with access to this panel can submit a colour.'})],components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`color_open:${id}`).setLabel('Choose Colour').setEmoji('🎨').setStyle(ButtonStyle.Primary))],allowedMentions:{parse:[] as []}};}
 private preview(id:string,userId:string,role:Role,value:number){const r=value>>16,g=(value>>8)&255,b=value&255;return {embeds:[glurpsEmbed().setTitle('🎨 Your Colour Preview').setColor(value).setDescription(`**Role:** <@&${role.id}>\n**Selected:** \`${colorHex(value)}\`\n**RGB:** \`${r}, ${g}, ${b}\`\n**Current role colour:** \`${colorHex(role.color)}\`\n\nNothing changes until you press **Apply Colour**.`).setFooter({text:'Pure black is mapped to #000001 because Discord uses #000000 for no colour.'})],components:[
 new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(`color_preset:${id}:${userId}`).setPlaceholder('Choose a colour preset').addOptions(presets.map(([name,hex])=>({label:name,value:hex,description:'#'+hex})))),
 new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`color_hex:${id}:${userId}`).setLabel('Enter Hex').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`color_light:${id}:${userId}`).setLabel('Lighter').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`color_dark:${id}:${userId}`).setLabel('Darker').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`color_random:${id}:${userId}`).setLabel('Random').setStyle(ButtonStyle.Secondary)),
 new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`color_apply:${id}:${userId}`).setLabel('Apply Colour').setEmoji('✅').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`color_reset:${id}:${userId}`).setLabel('Reset Preview').setStyle(ButtonStyle.Secondary))],allowedMentions:{parse:[] as []}};}
 async create(i:ChatInputCommandInteraction){await i.deferReply({flags:64});const selected=i.options.getRole('role',true);const role=await i.guild!.roles.fetch(selected.id);if(!role || role.managed || !role.editable || role.id===i.guildId)throw new Error('Choose a normal role below my highest role.');if(!i.channel?.isSendable())throw new Error('Use this in a channel where I can send messages.');const id=randomUUID();const message=await i.channel.send(this.publicPayload(id,role));sqlite.prepare('INSERT INTO color_picker_panels VALUES (?,?,?,?,?)').run(id,i.guildId,i.channelId,message.id,role.id);await i.editReply('Colour picker posted in this channel. Anyone here can choose and apply a colour.');}
 async button(i:ButtonInteraction){const [action,id,owner]=i.customId.split(':');const {p,role}=await this.target(i,id,owner);let value=this.getDraft(id,i.user.id,role);
  if(action==='color_open'){this.save(id,i.user.id,value);await i.reply({...this.preview(id,i.user.id,role,value),flags:64});return;}
  if(action==='color_hex'){await i.showModal(new ModalBuilder().setCustomId(`color_submit:${id}:${i.user.id}`).setTitle('Custom Role Colour').addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('hex').setLabel('Hex colour (e.g. #A78BFA)').setStyle(TextInputStyle.Short).setValue(colorHex(value)).setMinLength(3).setMaxLength(8).setRequired(true))));return;}
  if(action==='color_apply'){
   const key=`${p.guild_id}:${role.id}`;if(this.locks.has(key)){await i.reply({content:'Another colour is being applied. Try again in a moment.',flags:64});return;}this.locks.add(key);
   try {await i.deferUpdate();const old=role.color;await role.setColor(value,`Colour submitted by ${i.user.id} through an administrator-created picker.`);sqlite.prepare('INSERT INTO role_color_history VALUES (?,?,?,?,?,?)').run(p.guild_id,role.id,i.user.id,old,value,Date.now());await i.editReply({...this.preview(id,i.user.id,role,value),content:`✅ Applied **${colorHex(value)}** to **${role.name}**.`});const channel=await i.guild!.channels.fetch(p.channel_id);if(channel?.isTextBased())await channel.messages.edit(p.message_id,this.publicPayload(id,role));}
   finally{this.locks.delete(key);}return;
  }
  if(action==='color_light')value=brightness(value,.1);else if(action==='color_dark')value=brightness(value,-.1);else if(action==='color_random')value=Math.floor(Math.random()*0xffffff)+1;else if(action==='color_reset')value=role.color||0x5865f2;
  this.save(id,i.user.id,value);await i.update({...this.preview(id,i.user.id,role,value),content:''});
 }
 async select(i:StringSelectMenuInteraction){const [,id,owner]=i.customId.split(':');const {role}=await this.target(i,id,owner);const value=hexColor(i.values[0]);this.save(id,i.user.id,value);await i.update({...this.preview(id,i.user.id,role,value),content:''});}
 async modal(i:ModalSubmitInteraction){const [,id,owner]=i.customId.split(':');const {role}=await this.target(i,id,owner);let value;try{value=hexColor(i.fields.getTextInputValue('hex'));}catch(error){await i.reply({content:(error as Error).message,flags:64});return;}this.save(id,i.user.id,value);if(i.isFromMessage())await i.update({...this.preview(id,i.user.id,role,value),content:''});else await i.reply({...this.preview(id,i.user.id,role,value),flags:64});}
}
export const colorPickerService=new ColorPickerService();
